---

- name: configure_elastic | Configure Listening IP and Port
  lineinfile:
    path: "{{ elastic_conf }}"
    state: present
    create: yes
    mode: 0644
    owner: root
    group: elasticsearch
    line: '{{ item }}'
  loop:
    - 'network.host: "{{ elastic_server_ip }}"'
    - 'http.port: {{ elastic_port }}'
    - 'xpack.license.self_generated.type: basic'
    - 'cluster.initial_master_nodes: {{ elastic_server_ip }}'
      #    - 'path.data: {{ elastic_data_path }}'
    - 'bootstrap.memory.lock: true'


# Config elasticsearch.xml

      #- name: Copy templated to configuration directory
      #  template:
      #    src: "{{ item.src }}"
      #    dest: "{{ item.dest }}"
      #    owner: "{{ es_owner }}"
      #    group: "{{ es_group }}"
      #    mode: 0664
      #  with_items: "{{ es_template_files }}"
      #  register: es_templates


      #- name: configure_elastic | Configure SSL For Elasticsearch (if SSL True)
      #  lineinfile:
      #    path: "{{ elastic_conf }}"
      #    state: present
      #    line: "{{ item }}"
      #  loop:
      #    - "xpack.security.enabled: true"
      #    - "xpack.security.http.ssl.enabled: true"
      #    - "xpack.security.transport.ssl.enabled: true"
      #    - "xpack.security.transport.ssl.verification_mode: certificate"
      #    - "xpack.security.http.ssl.key: {{ elastic_cert_location }}{{ cert_pem_key_name }}"
      #    - "xpack.security.http.ssl.certificate: {{ elastic_cert_location }}{{ cert_pem_crt_name }}"
      #    - 'xpack.security.http.ssl.certificate_authorities: ["{{ elastic_cert_location }}{{ cert_ca_chain_name }}"]'
      #  when: ssl_on|bool

- name: configure_elastic | Start the Elastic Service
  service:
    name: elasticsearch
    enabled: true
    state: started
