---
# defaults file for ELK_Stack
auditbeat_conf: /etc/auditbeat/auditbeat.yml
auditbeat_template_path: "{{ template_dir }}/auditbeats.json"
beat_port: 5044
elastic_server_ip: localhost
elastic_port: 9200
filebeat_conf: /etc/filebeat/filebeat.yml
filebeat_template_path: "{{ template_dir }}/filebeats.json"
kibana_port: 5601
logstash_beat_conf: /etc/logstash/conf.d/01-beats-input.conf
logstash_output_conf: /etc/logstash/conf.d/30-elasticsearch-output.conf
logstash_sysfilter_conf: /etc/logstash/conf.d/10-syslog-filter.conf
replicas: 0
logstash_server_ip: localhost
shards: 1
template_dir: /etc/logstash/templates

#SSL Settings
cert_ca_chain_name: "elk.csr"
cert_location: /etc/ssl/
cert_pem_key_name: "elk.pem"
cert_pem_crt_name: "elk.crt"
logstash_cert_location: /etc/logstash/certs/
ssl_generate_cert: false
ssl_on: false
