---

- name: configure_beats | Load Filebeat Kibana Dashboard
  command: "/usr/bin/filebeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['{{ elastic_ server_ip}}:{{ elastic_port}}'] -E setup.kibana.host={{ kibana_server_ip }}:{{ kibana_port }}"
  changed_when: false

- name: configure_beats | Load Auditbeat Kibana Dashboard
  command: "/usr/bin/auditbeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['{{ elastic_server_ip}}:{{ elastic_port}}'] -E setup.kibana.host={{ kibana_server_ip }}:{{ kibana_port }}"
  changed_when: false

